## Growth under Allee effect

To set the stage for more complex derivations, we analyze the simple case of a single population experiencing an Allee effect: when the density of a population is below the critical threshold $\alpha$, the population declines; between $\alpha < y < \beta$, it grows; and, finally, it declines if the density is above $\beta$. Growth in this model can be represented as a cubic polynomial:

\begin{equation}
\dot{y} = y (y - \alpha) (\beta - y) = y(-\alpha \beta + (\alpha + \beta) y - y^2)
\end{equation}

Clearly, there are three equilibria, corresponding to the absence of the population, $y^\star = \alpha$, and $y^\star = \beta$. It is also fairly simple to show (for example using a graphical method, or a quadratic Lyapunov function) that any initial condition $y(0) < \alpha$ leads to the extinction of the population, while any initial density above $\alpha$ defines trajectories converging to $\beta$. We want to show that the equilibrium $y^\star = \beta$ is asymptotically stable for any trajectory starting at $y(0) > \alpha$. First, we rewrite the system in QP form, and then turn it into a two-dimensional GLV system:

\begin{equation}
\begin{aligned}
x = \begin{pmatrix}
y\\
y^2
\end{pmatrix}
\quad
s = \begin{pmatrix}
- \alpha \beta
\end{pmatrix}
\quad
M = \begin{pmatrix}
\alpha + \beta & -1
\end{pmatrix}
\quad
B = \begin{pmatrix}
1 \\
2
\end{pmatrix}
\\
r = Bs= \begin{pmatrix}
- \alpha \beta\\
- 2 \alpha \beta
\end{pmatrix}
\quad 
A = BM = \begin{pmatrix}
\alpha +  \beta & -1\\
2 (\alpha + \beta) & -2
\end{pmatrix}
\end{aligned}
\end{equation}

Clearly, the matrix $A$ has rank one. Now we consider the matrix $G = \frac{1}{2} (D(w)A + A^T D(w))$:

\begin{equation}
G = \begin{pmatrix}
w_1 (\alpha + \beta) & (\alpha + \beta) w_2 - \frac{1}{2} w_1\\
(\alpha + \beta) w_2 - \frac{1}{2} w_1 & - 2 w_2
\end{pmatrix}
\end{equation}

along with the perturbation $\Delta x = (y - y^\star, y^2 - {y^\star}^2)^T = (y - \beta, y^2 - \beta^2)^T$.
We find:

\begin{equation}
\dot{V} = -(y - \alpha) (\beta - y)^2 (w_1 + 2 w_2 (\beta + y))
\end{equation}

Because $(\beta - y)^2 (w_1 + 2 w_2 (\beta + y)) > 0$ for any choice of $w_1>0$ and $w_2>0$, then the function $\dot{V}$ is negative whenever $y > \alpha$ and $y \neq \beta$, proving stability (given that if $y(0) > \alpha$, then $y(t) > \alpha$ for every $t$). 


