## Leslie-Gower without intraspecific competition
\label{sec:lgnosr}

Take the Leslie-Gower model above and set the coefficient modeling intraspecific competition to zero. The model simplifies to:

\begin{equation}
\label{eq:lgnosr}
\begin{cases}
\dot{y}_1 = y_1 (\rho_1 - \alpha_1 y_2)\\
\dot{y}_2 = y_2 \left(\rho_2 - \alpha_2 \frac{y_2}{y_1} \right)
\end{cases}
\end{equation}

The model has a feasible equilibrium $y_1^\star = \alpha_2 \rho_1 / (\alpha_1 \rho_2)$, $y_2^\star = \rho_1 / \alpha_1$, and we want to prove that the equilibrium is globally attractive. 
We can identify two quasi-monomials (i.e., in this case $n = m$). As such, we can recast the model as a GLV with two equations. We define:

\begin{equation}
\begin{aligned}
x = \begin{pmatrix}
y_2\\
\frac{y_2}{y_1}
\end{pmatrix}
\quad
s = \begin{pmatrix}
\rho_1 \\
\rho_2
\end{pmatrix}
\quad
M = \begin{pmatrix}
-\alpha_1 & 0\\
0 & -\alpha_2
\end{pmatrix}
\quad
B = \begin{pmatrix}
0 & 1\\
-1 & 1
\end{pmatrix}
\\
r = Bs= \begin{pmatrix}
\rho_2\\
\rho_2 - \rho_1
\end{pmatrix}
\quad 
A = BM = \begin{pmatrix}
0 & -\alpha_2\\
\alpha_1 & -\alpha_2
\end{pmatrix}
\end{aligned}
\end{equation}

These parameters define a predator-prey GLV model in which the predator experiences intraspecific competition. The coexistence equilibrium is stable, as shown by considering the candidate Lyapunov function with weights $w = (1/\alpha_2,1/\alpha_1)^T$, and the perturbations $\Delta x = (\Delta x_1, \Delta x_2)^T = (y_2 - y_2^\star, y_2/y_1 - y_2^\star / y_1^\star)^T = (\Delta y_2, (y_2 y_1^\star - y_1 y_2^\star)/(y_1 y_1^\star))^T$. Deriving with respect to time, we obtain:

\begin{equation}
\dot{V} = \frac{1}{2} \Delta x^T (D(w) A + A^T D(w)) \Delta x =  - \frac{\alpha_2}{\alpha_1} \Delta x_2^2 = -\frac{\alpha_2}{\alpha_1} \left( \frac{y_2 y_1^\star - y_1 y_2^\star}{y_1 y_1^\star}\right)^2\leq 0
\end{equation}

Thus, $\dot{V} \leq 0$, with equality attained when $y_2 y_1^\star - y_1 y_2^\star$; when this is the case, the equation $\dot{y}_2 = 0$, and therefore the equilibrium is the only trajectory contained in the space defining $\dot{V} = 0$ and thus is globally stable.
