## Facultative mutualism with Type-II functional response

We consider a very simple model of facultative mutualism:

\begin{equation}
\begin{cases}
\dot{z}_1 = z_1 \left(\rho_1 - \alpha_1 z_1 + \beta_1 \frac{z_2}{(\gamma_2 + z_2)} \right)\\
\dot{z}_2 = z_2 \left(\rho_2 - \alpha_2 z_2 + \beta_2 \frac{z_1}{(\gamma_1 + z_1)} \right)
\end{cases}
\end{equation}

This model is not in QP form. We therefore need to create *auxiliary variables* in order to recast the system as a (typically, larger) QP model. We can then apply the same machinery and turn it into a (typically, even larger!) GLV model.

A convenient choice is to choose $y_3 = 1 / (\gamma_1 + z_1)$, because $\frac{\partial y_3}{\partial z_1} = - \frac{1}{(\gamma_1 + z_1)^2} = -y_3^2$, and as such $\dot{y}_3 = -y_3^2 \dot{z}_1$, guaranteeing that the result will be a QP system.

We therefore define $y_1 = z_1$, $y_2 = z_2$, $y_3 = 1/(\gamma_1 + z_1)$ and $y_4 = 1 / (\gamma_2 + z_2)$, resulting in a four-dimensional QP system:

\begin{equation}
\begin{cases}
\dot{y}_1 = y_1 \left(\rho_1 - \alpha_1 y_1 + \beta_1 y_2 y_4 \right)\\
\dot{y}_2 = y_2 \left(\rho_2 - \alpha_2 y_2 + \beta_2 y_1 y_3 \right)\\
\dot{y}_3 = -y_3^2 \dot{y}_1 = y_3 (-\rho_1 y_1 y_3 + \alpha_1 y_1^2 y_3 - \beta_1 y_1 y_2 y_3 y_4)\\
\dot{y}_4 = -y_4^2 \dot{y}_2 = y_4 (-\rho_2 y_2 y_4 + \alpha_2 y_2^2 y_4 - \beta_2 y_1 y_2 y_3 y_4)
\end{cases}
\end{equation}

We now proceed as before: we identify seven quasi-monomials, and represent the system as a GLV model:

\begin{equation}
\begin{aligned}
s = \begin{pmatrix}
\rho_1\\
\rho_2\\
0 \\
0
\end{pmatrix}
\quad 
B = \begin{pmatrix}
1 & 0 & 0 & 0\\
0 & 1 & 0 & 0\\
1 & 0 & 1 & 0\\
0 & 1 & 0 & 1\\
2 & 0 & 1 & 0\\
0 & 2 & 0 & 1\\
1 & 1 & 1 & 1
\end{pmatrix}
\quad 
M = \begin{pmatrix}
-\alpha_1  & 0  & 0 & \beta_1 & 0 & 0 & 0\\
0 & -\alpha_2  & \beta_2 & 0 & 0 & 0 & 0\\
0 & 0 & -\rho_1 & 0 & \alpha_1 & 0 & -\beta_1\\
0 & 0 & 0 & -\rho_2 & 0 & \alpha_2 & -\beta_2
\end{pmatrix}\\
x = \begin{pmatrix}
y_1\\
y_2\\
y_1 y_3\\
y_2 y_4\\
y_1^2 y_3\\
y_2^2 y_4\\
y_1 y_2 y_3 y_4
\end{pmatrix}
\quad
r = \begin{pmatrix}
\rho_1 \\
\rho_2 \\
\rho_1 \\
\rho_2 \\
2 \rho_1 \\
2 \rho_2 \\
\rho_1+\rho_2
\end{pmatrix}
\quad
A = \begin{pmatrix}
-\alpha_1 & 0 & 0 & \beta_1 & 0 & 0 & 0 \\
 0 & -\alpha_2 & \beta_2 & 0 & 0 & 0 & 0 \\
 -\alpha_1 & 0 & -\rho_1 & \beta_1 & \alpha_1 & 0 & -\beta_1 \\
 0 & -\alpha_2 & \beta_2 & -\rho_2 & 0 & \alpha_2 & -\beta_2 \\
 -2 \alpha_1 & 0 & -\rho_1 & 2 \beta_1 & \alpha_1 & 0 & -\beta_1 \\
 0 & -2 \alpha_2 & 2 \beta_2 & -\rho_2 & 0 & \alpha_2 & -\beta_2 \\
 -\alpha_1 & -\alpha_2 & \beta_2-\rho_1 & \beta_1-\rho_2 & \alpha_1 & \alpha_2 & -\beta_1-\beta_2
\end{pmatrix}
\end{aligned}
\end{equation}

Despite the complicated appearance, it is possible to prove the stability of the model in a straightforward way: choose the first two weights ($w_1, w_2$) to be positive, and all other weights to be zero. The matrix $G = \frac{1}{2}(D(w)A + A^T D(w))$ becomes very sparse, yielding:

\begin{equation}
\dot{V} = \Delta x^T G \Delta x = w_1 \Delta x_1 (\beta_1 \Delta x_4 - \alpha_1 \Delta x_1) + w_2 \Delta x_2 (\beta_2 \Delta x_3 - \alpha_2 \Delta x_2)
\end{equation}

Substituting the perturbations measured in the QP, and then the original coordinates, $\Delta x_1 = \Delta y_1 = \Delta z_1$, $\Delta x_2 = \Delta y_2 = \Delta z_2$, $\Delta x_3 = y_1 y_3 - y_1^\star y_3^\star = z_1 / (\gamma_1 + z_1) - z_1^\star / (\gamma_1 + z_1^\star) = \gamma_1 \Delta z_1 / ((\gamma_1 + z_1) (\gamma_1 + z_1^\star))$, $\Delta x_4 = \gamma_2 \Delta z_2 / ((\gamma_2 + z_2) (\gamma_2 + z_2^\star))$, the expression reduces to:

\begin{equation}
\dot{V} = - \alpha_1 w_1 \Delta z_1^2 - \alpha_2 w_2 \Delta z_2^2 + \Delta z_1 \Delta z_2 \left(\frac{\gamma_2 \beta_1 w_1}{(\gamma_2 +z_2)(\gamma_2 +z_2^\star)} + \frac{\gamma_1 \beta_2 w_2}{(\gamma_1 +z_1)(\gamma_1 +z_1^\star)} \right)
\end{equation}

Naturally, the first two terms are negative (as long as the two weights are positive), and the coefficients in parenthesis are positive. As such whenever $\Delta z_1 \Delta z_2 \leq 0$, $\dot{V} \leq 0$. When this is not the case, we can bound the function from above:

\begin{equation}
\begin{aligned}
\dot{V} &\leq - \alpha_1 w_1 \Delta z_1^2 - \alpha_2 w_2 \Delta z_2^2 + \Delta z_1 \Delta z_2 \left(\frac{\beta_1 w_1}{(\gamma_2 +z_2^\star)} + \frac{\beta_2 w_2}{(\gamma_1 +z_1^\star)} \right)\\
&\leq - \alpha_1 w_1 \Delta z_1^2 - \alpha_2 w_2 \Delta z_2^2 + \Delta z_1 \Delta z_2 \left(w_1 \frac{\alpha_1 z_1^\star - \rho_1}{z_2^\star} + w_2 \frac{\alpha_2 z_2^\star- \rho_2}{z_1^\star} \right)\\
&\leq - \alpha_1 w_1 \Delta z_1^2 - \alpha_2 w_2 \Delta z_2^2 + \Delta z_1 \Delta z_2 \left(w_1 \frac{\alpha_1 z_1^\star}{z_2^\star} + w_2\frac{\alpha_2 z_2^\star}{z_1^\star} \right)
\end{aligned}
\end{equation}

Finally, choosing $w_1 = 1 / (\alpha_1 z_1^2)$ and $w_2 = 1 / (\alpha_2 z_2^2)$, we obtain:

\begin{equation}
\begin{aligned}
\dot{V} &\leq -\frac{1}{(z_1^\star)^2} \Delta z_1^2 + 2 \Delta z_1 \Delta z_2 \frac{1}{z_1^\star z_2^\star} - -\frac{1}{(z_2^\star)^2} \Delta z_2^2 \\
&\leq - \left(\frac{\Delta z_1}{z_1^\star} - \frac{\Delta z_2}{z_2^\star}\right)^2 \\
&\leq 0
\end{aligned}
\end{equation}


